// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/QuePlatform/GoSDK/models/components"
)

type GetHealthCheckResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Service is healthy and operational.
	HealthzResponse *components.HealthzResponse
}

func (g *GetHealthCheckResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetHealthCheckResponse) GetHealthzResponse() *components.HealthzResponse {
	if g == nil {
		return nil
	}
	return g.HealthzResponse
}
