// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/QuePlatform/GoSDK/models/components"
)

type GetPresignedURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A presigned URL and object key were successfully generated.
	PresignResponse *components.PresignResponse
	Headers         map[string][]string
}

func (g *GetPresignedURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPresignedURLResponse) GetPresignResponse() *components.PresignResponse {
	if g == nil {
		return nil
	}
	return g.PresignResponse
}

func (g *GetPresignedURLResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
