// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/QuePlatform/GoSDK/models/components"
)

type GetTrustListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The current trust list.
	TrustListResponse *components.TrustListResponse
	Headers           map[string][]string
}

func (g *GetTrustListResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTrustListResponse) GetTrustListResponse() *components.TrustListResponse {
	if g == nil {
		return nil
	}
	return g.TrustListResponse
}

func (g *GetTrustListResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
