// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/QuePlatform/GoSDK/models/components"
)

type SignAssetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The asset was successfully signed.
	SignResponse *components.SignResponse
	Headers      map[string][]string
}

func (s *SignAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SignAssetResponse) GetSignResponse() *components.SignResponse {
	if s == nil {
		return nil
	}
	return s.SignResponse
}

func (s *SignAssetResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
