// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/QuePlatform/GoSDK/models/components"
)

type VerifyAssetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Verification report successfully generated.
	VerifyResponse *components.VerifyResponse
	Headers        map[string][]string
}

func (v *VerifyAssetResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VerifyAssetResponse) GetVerifyResponse() *components.VerifyResponse {
	if v == nil {
		return nil
	}
	return v.VerifyResponse
}

func (v *VerifyAssetResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
