// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/QuePlatform/GoSDK/internal/utils"
)

// CawgVerifyDto - Options controlling CAWG identity validation behavior during verification.
type CawgVerifyDto struct {
	// Whether to run CAWG identity validation.
	Validate *bool `default:"true" json:"validate"`
	// Whether to fail verification if CAWG identity is missing/invalid.
	RequireValidIdentity *bool `default:"false" json:"require_valid_identity"`
}

func (c CawgVerifyDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CawgVerifyDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CawgVerifyDto) GetValidate() *bool {
	if c == nil {
		return nil
	}
	return c.Validate
}

func (c *CawgVerifyDto) GetRequireValidIdentity() *bool {
	if c == nil {
		return nil
	}
	return c.RequireValidIdentity
}
