// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HealthzResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	// The Unix epoch timestamp when the health check was performed.
	Timestamp int64 `json:"timestamp"`
}

func (h *HealthzResponse) GetStatus() string {
	if h == nil {
		return ""
	}
	return h.Status
}

func (h *HealthzResponse) GetMessage() string {
	if h == nil {
		return ""
	}
	return h.Message
}

func (h *HealthzResponse) GetTimestamp() int64 {
	if h == nil {
		return 0
	}
	return h.Timestamp
}
