// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PresignResponse - A presigned URL and object key for secure S3 upload. Use the URL to upload your asset directly to S3, then use the returned key for signing/verification operations.
type PresignResponse struct {
	// The presigned S3 URL for direct upload. Make a PUT request to this URL with your asset file as the body. The URL is valid for a limited time (typically 15 minutes).
	URL string `json:"url"`
	// The S3 object key where your asset will be stored. Use this key in subsequent sign/verify API calls to reference the uploaded asset.
	Key string `json:"key"`
}

func (p *PresignResponse) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *PresignResponse) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}
