// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/QuePlatform/GoSDK/internal/utils"
)

// PresignedURL - An asset accessible via HTTP/HTTPS URL. The URL must be enabled via the ALLOW_URL_ASSETS environment variable. The service will stream the file to temporary storage during processing.
type PresignedURL struct {
	// The HTTP/HTTPS URL of the asset. Must be publicly accessible.
	URL string `json:"url"`
}

func (p PresignedURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PresignedURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (p *PresignedURL) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}
