// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/QuePlatform/GoSDK/internal/utils"
)

// S3 - An asset located in an S3 bucket that the Que service has access to. The service will stream the file from S3 to temporary storage during processing.
type S3 struct {
	// The name of the S3 bucket.
	Bucket string `json:"bucket"`
	// The object key (path) within the S3 bucket.
	Key string `json:"key"`
}

func (s S3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *S3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"bucket", "key"}); err != nil {
		return err
	}
	return nil
}

func (s *S3) GetBucket() string {
	if s == nil {
		return ""
	}
	return s.Bucket
}

func (s *S3) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}
