// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	APIKeyAuth *string `security:"scheme,type=apiKey,subtype=header,name=x-api-key,env=que_api_key_auth"`
}

func (s *Security) GetAPIKeyAuth() *string {
	if s == nil {
		return nil
	}
	return s.APIKeyAuth
}
