// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VerifyResponse - The result of a C2PA manifest verification operation.
type VerifyResponse struct {
	// JSON string containing the verification report from the C2PA engine. The structure varies based on the verification mode requested.
	Report string `json:"report"`
}

func (v *VerifyResponse) GetReport() string {
	if v == nil {
		return ""
	}
	return v.Report
}
