// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/QuePlatform/GoSDK/models/components"
)

// ProblemResponseError - An RFC 7807 problem details response.
type ProblemResponseError struct {
	Type     string                  `json:"type"`
	Title    string                  `json:"title"`
	Status   int64                   `json:"status"`
	Code     string                  `json:"code"`
	Detail   *string                 `json:"detail,omitempty"`
	Details  *components.Details     `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ProblemResponseError{}

func (e *ProblemResponseError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
